name: Metrics
on:
  # Schedule updates (every 24 hours at midnight)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run it manually from the Actions tab
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: armin-gs
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York # Update this if you are not in EST
          
          # This saves the image to your repo
          filename: github-metrics.svg
          output_action: commit
          committer_branch: master # IMPORTANT: Change to 'main' if your branch is main
          committer_message: "chore: update metrics"
